sudo: enabled
notifications:
  email: false
language: python
python:
- '3.6'
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda update --yes pip
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION coverage python-dateutil numpy
  scipy matplotlib pandas statsmodels
- python setup.py install
script: coverage run -m unittest discover epcy/tests/
after_success: bash <(curl -s https://codecov.io/bash)
